In [1]:
import torch

In [17]:
scalar=torch.tensor(3.12)
scalar

tensor(3.1200)

In [18]:
scalar.item()

3.119999885559082

In [19]:
scalar.ndim

0

In [20]:
sc=torch.tensor([[[[]]],[[[]]],[[[]]]])
sc

tensor([], size=(3, 1, 1, 0))

In [21]:
sc

tensor([], size=(3, 1, 1, 0))

In [22]:
ra=torch.rand(3,3)
ra

tensor([[0.0867, 0.1786, 0.4535],
        [0.2022, 0.4263, 0.8896],
        [0.8046, 0.2642, 0.4097]])

In [23]:
ra=torch.randint(0,10,(3,3))
ra

tensor([[3, 5, 8],
        [2, 6, 2],
        [8, 7, 3]])

In [24]:
ra=torch.range(0,10)
ra

C:\Users\Vasantha Raj\AppData\Local\Temp\ipykernel_21968\1664205149.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ra=torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
ra=torch.arange(0,10,0.2)
ra

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

In [26]:
ra=torch.linspace(0,10,20)
ra

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [27]:
ra=torch.zeros(3,3)
ra

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
ra=torch.ones(3,3)
ra

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
ra=torch.eye(3,dtype=torch.float32)
ra

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

32 bit - torch.float32|torch.float,torch.FloatTensor,torch.cuda.FloatTensor

64 bit - torch.float64|torch.double,torch.DoubleTensor,torch.cuda.DoubleTensor

16 bit torch.float16|torch.half,torch.HalfTensor,torch.cuda.HalfTensor

torch.complex32

dtype

device

requires_grad

attribute problems of tensor

tensor not right datatype tensor.dtype

tensor not right shape tensor.shape

tensor not right device tensor.device

Tensor operations include :

Addition, subtraction, multiplication (element wise), Division, Matrix multiplication

In [30]:
# ra=torch.rand(3,3 ,dtype=torch.cuda.FloatStorage)
# ra

In [31]:
t=torch.tensor([[[10,20,30]],[[20,30,50]]])
t1=torch.tensor([[-10],[-10],[-5]])
t+t1

tensor([[[ 0, 10, 20],
         [ 0, 10, 20],
         [ 5, 15, 25]],

        [[10, 20, 40],
         [10, 20, 40],
         [15, 25, 45]]])

two main ways of performing multiplication in neural networks and deep learning

element wise multiplication

matrix dot product torch.matmul or @ (operator for matric multiplication)

    inner dimensions should satisfy the multiplication condition

    resulting matrix has the shape of the outer dimension

tensor aggregation min, max, mean and sum (torch.aggmethod(tensor) or tensor.aggmethod())

positional min and max 

tensor.argmin(),tensor.argmax()

indexing, reshaping, stacking, squeezing and unsqueesing

* reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original  tensor
* stacking - concatenating a sequence of tensors along a new dimension.
* squeeze - remove all '1' dimensions from a tensor
* unsqueeze - add a 1 dimension to a target tensor
* permute - return a view of the input with dimensions permuted in a certain way


In [32]:
t.shape,t1.shape

(torch.Size([2, 1, 3]), torch.Size([3, 1]))

In [33]:
%%time
import sklearn

CPU times: total: 766 ms
Wall time: 5.92 s


* tensor.reshape(shape)
* tensor.view(shape)
* tensor.stack([tensors],dim=0 or 1)
* torch.sqeeze(tensor) or tensor.squeeze()

In [34]:
ra

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [35]:
ra.permute(1,0)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
ra.T

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Pytorch tensors and numpy nd arrays

pytorch has functionality to interact with it.

* Data in numpy what in pytorch -> torch.from_numpy(ndarray)
* pytorch tensor -> numpy -> torch.Tensor.numpy()

Pytorch Reproducibility (Taking the random out of random)

torch.manual_seed(seed)

**Running tensors and pytorch object on GPU**


device agnostic code of argparse  https://pytorch.org/docs/stable/notes/cuda.html#best-practices


GPU to CPU and vice vers - learn!!


In [37]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [38]:
torch.cuda.device_count()

0

In [39]:
torch.__version__

'2.1.0+cu118'

pytorch model building essentials

* torch.nn - contains all of the buildings for computational graphs (a neural network can be considered a computational graph)
* torch.nn.Parameter - what parameters should our model try and learn, often a pytorch layer from torch.nn will set these for us
* torch.nn.Module - the base class for all neural network modules, if you subclass it, you should overwrite forward()
* forward method

In [42]:
# pytorch.org/tutorials/beginner/ptcheat.html

neural network api libraries

In [43]:
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim 
import torch.autograd as autograd 
from torch import Tensor 

general

In [44]:
import torch
from torch.utils.data import Dataset,DataLoader 

ONNX

there are two versions of the exporter

torchdynamo-based onnx exporter
    
torchscript-based onnx exporter

FX grpah - tracer

In [45]:
torch.onnx.export(model,dummy data,xxxx.proto) #exports as onnx formatted model using a trained model, dummy data and the desired file name

model=torch.onnx.load('alexnet.proto') #load an onnx model
torch.onnx.checker.check_model(model) #check that the model is well formed


torch.onnx.helper.printable_graph(model.graph) #print a human readable representaton of the graph

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2527913872.py, line 1)

first model

In [61]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.mod=Linear()
        self.weight=nn.Parameter(torch.randn(1,requires_grad=True))

    def forward(self):

        return self.weight*self.mod.forward()
class Linear(nn.Module):
    def __init__(self):
        super().__init__()
        self.we=nn.Parameter(torch.randn(1,requires_grad=True) )
    def forward(self):
        return self.we

In [62]:
model=LinearModel()
model

LinearModel(
  (mod): Linear()
)

In [63]:
list(model.parameters())

[Parameter containing:
 tensor([1.8969], requires_grad=True),
 Parameter containing:
 tensor([-1.4213], requires_grad=True)]

difference modes in pytorch

with torch.inference_mode()

with torch.no_grad()

model.train()

optimizer.zero_grad()

loss.backward()

optimizer.step()

model.eval()

set up loss function and optimizer

* buiilding a training loop

couple of things we need in a training loop

oop through the data

forward pass to make predictions on data

calculate the loss 

optimizer zero grad

loss backward

optimizer step

we can define our own way of loss functions other than torch implemented functions, but the loss function should be differentiable

there are three main methods we should about for saving and loading models in pytorch

1. torch.save() - allows us to save a pytorch object in python's pickle format
2. torch.load() - allows us to load a saved pytorch object
3. torch.nn.Module.load_state_dict() - allows us to load a model's saved state dictionary