In [1]:
import torch

In [2]:
scalar=torch.tensor(3.12)
scalar

tensor(3.1200)

In [3]:
scalar.item()

3.119999885559082

In [4]:
scalar.ndim

0

In [16]:
sc=torch.tensor([[[[]]],[[[]]],[[[]]]])
sc

tensor([], size=(3, 1, 1, 0))

In [10]:
sc

tensor([], size=(3, 3, 1, 0))

In [17]:
ra=torch.rand(3,3)
ra

tensor([[0.9580, 0.1325, 0.8639],
        [0.1740, 0.0252, 0.3117],
        [0.1423, 0.0963, 0.8395]])

In [18]:
ra=torch.randint(0,10,(3,3))
ra

tensor([[9, 7, 9],
        [7, 2, 0],
        [2, 6, 2]])

In [20]:
ra=torch.range(0,10)
ra

C:\Users\Vasantha Raj\AppData\Local\Temp\ipykernel_37040\1664205149.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ra=torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
ra=torch.arange(0,10,0.2)
ra

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

In [26]:
ra=torch.linspace(0,10,20)
ra

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [27]:
ra=torch.zeros(3,3)
ra

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
ra=torch.ones(3,3)
ra

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
ra=torch.eye(3,dtype=torch.float32)
ra

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
ra=torch.eye(3,dtype=torch.bfloat16)

TypeError: 'torch.dtype' object is not callable